-- require('config.nvim-lspconfig')
require('config.colorscheme')
require('config.quickscope')
require('config.bufferline')
require('config.galaxyline')
require('config.compe-config')
require('config.treesitter')
require('config.autopairs')
require('config.nvimtree')
require('config.kommentary')
require('config.gitsigns')
require('config.telescope')
require('config.lspinstall')
require('config.lightspeed')
require('config.ultisnips')
require('config.formatter')
