-- require('config.nvim-lspconfig')
require('config.colorscheme')
require('config.quickscope')
--require('config.airline')
require('config.barbar')
require('config.galaxyline')
--require('config.barbar')
require('config.compe-config')
require('config.treesitter')
require('config.autopairs')
require('config.nvimtree')
require('config.comment')
require('config.gitsigns')
require('config.telescope')
