require("globals")
require("settings")
require("plugins")
-- require('config.cmp')
require("lsp")
require("config.stabilize")
require("config.treesitter")
-- require('config.autopairs')
require("config.comment")
require("config.focus")
require("config.catppuccin")
require("config.bufferline")
require("config.lsp-kind")
require("config.telescope")
require("config.gitsigns")
require("autogroups")
require("mappings")
