#!/bin/bash 

Bat=$(acpi | cut -d " " -f4 | tr -d "%,"|tail -1)
Adapt=$(acpi -a | cut -d " " -f3|tail -1)
Remain=$(acpi|cut -d" " -f5|tail -1)
Full=$(acpi|grep -c Full)

if [ "$Adapt" = "on-line" ];then
    icon0=""
    icon1=""
    icon2=""
    icon3=""
    icon4=""
else
    icon0=""
    icon1=""
    icon2=""
    icon3=""
    icon4=""
fi

COLOR=""

if [ "$Full" -eq 1 ]; then
    Bat=100
fi

if [ -z "$Bat" ];then 
    bat=""
elif [ "$Bat" -ge "99" ];then 
     bat="$icon4 Full"
elif [ "$Bat" -gt "90" ];then 
     bat="$icon3 $Bat % ${Remain}"
     COLOR="#00FF00"
elif [ "$Bat" -gt "60" ];then 
     bat="$icon2 $Bat % ${Remain}"
     COLOR="#FFF600"
elif [ "$Bat" -gt "30" ];then 
     bat="$icon1 $Bat % ${Remain}"
     COLOR="#FFF600"
elif [ "$Bat" -le "30" ];then
     bat="$icon0 $Bat % ${Remain}"
     COLOR="#FF0000"
fi

echo -e "$bat"
echo -e "$bat"
echo "$COLOR"
