#!/bin/bash

MS="${BLOCK_INSTANCE:-40}"
C=""
COLOR=""

GW=$(/usr/bin/ip route|/usr/bin/grep '^default'|/usr/bin/awk '{print $3}'|/usr/bin/egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
if [ "$?" -ne 0 ]; then
    COLOR="#FF0000"
fi

/usr/bin/ping -c1 google.com >/dev/null 2>&1
if [ "$?" -ne 0 ]; then
    COLOR="#6034EF"
fi

RES=$(/usr/bin/ping -c1 "$GW"|/usr/bin/grep '^rtt'|/usr/bin/cut -d'/' -f6|/usr/bin/cut -d. -f1)
if [ "$?" -ne 0 ]; then
    COLOR="#FF0000"
fi

if [ "$RES" -gt "$MS" ]; then
    COLOR="#FFAE00"
fi

if [ ! -z "$COLOR" ]; then
    echo "$C"
    echo "$C"
    echo "$COLOR"
fi
exit 0
