#!/bin/bash

COLOR="#FFFFFF"
case "$(xset -q|grep LED| awk '{ print $10 }')" in
    "00000000") KBD="DK" ;;
    "00000001") COLOR="#FF0000"; KBD="CAPS DK" ;;
    "00001000") KBD="US" ;;
    "00001001") COLOR="#FF0000"; KBD="CAPS US" ;;
    *) KBD="unknown" ;;
esac

echo " $KBD" # full text
echo " $KBD" # short text
echo "$COLOR"
