#!/bin/bash

CONFIG="${BLOCK_INSTANCE:-default}"
PFILE="/var/run/${CONFIG}.pid"
if [ -e "${PFILE}" ]; then
    COLOR="#FF0000"
    if [ "$(ip address show dev tun0|egrep -c 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')" -ge 1 ]; then
        if [ "$(ip r|grep -c tun0)" -ge 1 ]; then
            COLOR="#FFFFFF"
        fi
    fi
    echo "${BLOCK_INSTANCE}" # long
    echo "${BLOCK_INSTANCE}" # short
    echo "${COLOR}"
else
    echo -e ""
fi
