#!/bin/bash

pacaur -Sya > /dev/null 2>&1
updates=$(/usr/bin/pacaur -Qu|/usr/bin/wc -l)
aur=$(/usr/bin/pacaur -Qu|grep aur|awk '{print $2}'|/usr/bin/wc -l)

pacman=$(( updates - aur ))

color="#00FF00"

if [ "$pacman" -gt 1 ]; then
    color="#FFF600"
fi

if [ "$updates" -gt 1 ]; then
    echo " $pacman/$aur"
    echo " $pacman/$aur"
    echo "$color"
fi


