#!/bin/bash

SINK=$(pacmd list-sinks|egrep -i 'index:'|grep '*'|awk '{print $3}')
if [ -z "$SINK" ];then
    SINK="0"
fi

N=$(pactl list sinks short|grep "^${SINK}"|awk '{print $2}'|cut -d. -f2-|cut -d- -f2-)

case $N in
    *FiiO*)
        NAME="FiiO"
        ;;
    *hdmi*)
        NAME="hdmi"
        ;;
    *)
        NAME="analog"
        ;;
esac

VOL=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
MUTE=$(pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1|cut -d: -f2|awk '{print $1}')

STR=""
if [ "${MUTE}" == 'yes' ]; then
    STR=""
fi

printf "%s %s %s\n" ${STR} ${VOL} ${NAME}
printf "%s %s %s\n" ${STR} ${VOL} ${NAME}

