#!/bin/bash

MIXER="default"
lsmod|grep -q pulse && MIXER="pulse"
lsmod|grep -q jack && MIXER="jackplug"

MIXER="${2:-$MIXER}"

CONTROLLER=$(amixer -D default scontrols |grep '^Simple'|head -n1|cut -d\' -f2)

PLAYBACK=$(amixer -D ${MIXER} get ${CONTROLLER}|egrep 'Front Left.*]$')

ONOFF=$(echo $PLAYBACK|cut -d'[' -f3|cut -d']' -f1)
VOL=$(echo $PLAYBACK|cut -d'[' -f2|cut -d']' -f1)

STR=""
if [ "${ONOFF}" == 'off' ]; then
    STR=""
fi

printf "%s %s\n" ${STR} ${VOL}
printf "%s %s\n" ${STR} ${VOL}
